
.darksands:
  0: &accent ffd5a0ff
  1: &text   C2BAB2ff

  2: &ok     89b482ff
  3: &pink   d3869bff

  4: &error  ea6962ff
  5: &warn   e78a4eff
  6: &info   7daea3ff

  7: &layer0 191817ff
  8: &layer1 232020ff
  9: &layer2 2b2828ff
  10: &layer3 353232ff
  11: &layer4 3f3c3cff

bar:
  height: 50
  location: top
  background: 00000000
  font: JetBrainsMonoNF:pixelsize=30
  foreground: *accent
  spacing: 10
  left:
    - dwl:
        number-of-tags: 9
        dwl-info-filename: /tmp/dwltags
        content:
          map:
            default:
              string:
                text: "{name}"
                margin: 10
                foreground: *layer2
                deco:
                  stack:
                    - background: {color: *layer0}
                    - border:
                        color: *layer2
                        size: 3
            conditions:
              id == 0:
                list:
                  spacing: 10
                  items:
                    - string:
                        text: ""
                        margin: 0

                    - string:
                        text: "{layout}"
                        foreground: *accent
                        margin: 10
                        deco:
                          stack:
                            - background: {color: *layer0}
                            - border:
                                color: *layer2
                                size: 3
                    - map:
                        default:
                          string:
                            text: ""
                        conditions:
                          appid != "":
                              list:
                                margin: 10
                                deco:
                                  stack:
                                    - background: {color: *layer0}
                                    - border:
                                        color: *layer2
                                        size: 3

                                items:
                                  - string:
                                      text: "({appid}) "
                                      foreground: *text

                                  - string:
                                      text: "{title}"
                                      foreground: *text
              urgent:
                string:
                  margin: 10
                  text: "{name}"
                  foreground: *layer0
                  deco:
                    stack:
                      - background: {color: *accent}
                      - border:
                          color: *layer2
                          size: 3
              selected && ~empty:
                string:
                  margin: 10
                  text: "{name}"
                  foreground: *accent
                  deco:
                    stack:
                      - background: {color: *layer0}
                      - border:
                          color: *layer2
                          size: 3
                      - underline:
                          color: *accent
                          size: 3
              ~empty:
                string:
                  margin: 10
                  text: "{name}"
                  foreground: *text
                  deco:
                    stack:
                      - background: {color: *layer0}
                      - border:
                          color: *layer2
                          size: 3
              selected:
                string:
                  margin: 10
                  text: "{name}"
                  foreground: *layer2
                  deco:
                    stack:
                      - background: {color: *layer0}
                      - border:
                          color: *layer2
                          size: 3
                      - underline:
                          color: *accent
                          size: 3

  right:
    # - network:
    #     poll-interval: 3000
    #     name: "eno2"
    #     content:
    #       map:
    #         default:
    #             string:
    #               text: " ({state})"
    #               foreground: e04040ff
    #               margin: 10
    #               deco: 
    #                 stack: 
    #                   - background: {color: *layer0}
    #                   - border: 
    #                       color: *layer2
    #                       size: 3
    #         conditions:
    #           state == up:
    #             list:
    #               items:
    #                 - string:
    #                     text: " {ul-speed:mib}MiB/s"
    #                     margin: 10
    #                     foreground: 009020ff
    #                     deco: 
    #                       stack: 
    #                         - background: {color: *layer0}
    #                         - border: 
    #                             color: *layer2
    #                             size: 3
    #                 - string:
    #                     text: " {dl-speed:mib}MiB/s"
    #                     margin: 10
    #                     foreground: e04040ff
    #                     deco: 
    #                       stack: 
    #                         - background: {color: *layer0}
    #                         - border: 
    #                             color: *layer2
    #                             size: 3


    - cpu:
        poll-interval: 3000
        content:
          map:
            conditions:
              id == -1:
                - string:
                    foreground: *accent
                    text: "cpu {cpu}%"
                    margin: 10
                    deco: 
                      stack: 
                        - background: {color: *layer0}
                        - border: 
                            color: *layer2
                            size: 3

    - mem:
        poll-interval: 3000
        content:
          string:
            foreground: *accent
            text: "mem {percent_used}%"
            margin: 10
            deco: 
              stack: 
                - background: {color: *layer0}
                - border: 
                    color: *layer2
                    size: 3

    - script:
        poll-interval: 3000
        path: "~/.config/yambar/screenshare_state.sh"
        content:
          map:
            conditions:

              sharing:
                - string:
                    foreground: *error
                    text: "󰍹 󰑊"
                    margin: 10
                    deco: 
                      stack: 
                        - background: {color: *layer0}
                        - border: 
                            color: *layer2
                            size: 3

    - pulse:
        content:
          list:
            spacing: 0
            items:
              - string:
                  text: "󰍬 {source_percent}%"
                  margin: 10
                  deco: 
                    stack: 
                      - background: {color: *layer0}
                      - border: 
                          color: *layer2
                          size: 3
              - string:
                  text: "󰕾 {sink_percent}%"
                  margin: 10
                  deco: 
                    stack: 
                      - background: {color: *layer0}
                      - border: 
                          color: *layer2
                          size: 3

#   - label:
#       content:
#         string:
#           margin: 20
#           text: ""
 
#   - script:
#       poll-interval: 3000
#       path: "~/.config/yambar/nvidia_gpu.sh"
#       content:
#         list:
#           spacing: 0
#           items:
#             - string:
#                 foreground: *accent
#                 text: "gpu {gpu_percent_used}%"
#                 margin: 10
#                 deco: 
#                   stack: 
#                     - background: {color: *layer0}
#                     - border: 
#                         color: *layer2
#                         size: 3
#             - string:
#                 foreground: *accent
#                 text: "vram {mem_percent_used}%"
#                 margin: 10
#                 deco: 
#                   stack: 
#                     - background: {color: *layer0}
#                     - border: 
#                         color: *layer2
#                         size: 3

  center:
    - clock:
        time-format: "%I:%M %p"
        date-format: "%d/%m/%Y (%a %b)"
        content:
          list:
            spacing: 10
            items:
              - string:
                  text: " {time}"
                  margin: 10
                  deco: 
                    stack: 
                      - background: {color: *layer0}
                      - border: 
                          color: *layer2
                          size: 3
              - string:
                  text: " {date}"
                  margin: 10
                  deco: 
                    stack: 
                      - background: {color: *layer0}
                      - border: 
                          color: *layer2
                          size: 3


