.base16:
  0: &base00 32302fff
  1: &base01 3c3836ff
  2: &base02 5a524cff
  3: &base03 7c6f64ff
  4: &base04 bdae93ff
  5: &base05 ddc7a1ff
  6: &base06 ebdbb2ff
  7: &base07 fbf1c7ff


bar:
  height: 50
  location: top
  background: 00000000
  font: JetBrainsMonoNerdFont:pixelsize=30
  foreground: *base05
  spacing: 0
  left:
    - dwl:
        number-of-tags: 9
        dwl-info-filename: /tmp/dwltags
        content:
          map:
            default:
              string:
                text: "{name}"
                margin: 10
                foreground: *base02
                deco:
                  stack:
                    - background: {color: *base00}
                    - border:
                        color: *base02
                        size: 3
            conditions:
              id == 0:
                list:
                  spacing: 10
                  items:
                    - string:
                        text: ""
                        margin: 0

                    - string:
                        text: "{layout}"
                        margin: 10
                        deco:
                          stack:
                            - background: {color: *base00}
                            - border:
                                color: *base02
                                size: 3
                    - map:
                        default:
                          string:
                            text: ""
                        conditions:
                          appid != "":
                              string:
                                  text: "{appid} ({title})"
                                  foreground: *base07
                                  margin: 10
                                  deco:
                                    stack:
                                      - background: {color: *base00}
                                      - border:
                                          color: *base02
                                          size: 3
              urgent:
                string:
                  margin: 10
                  text: "{name}"
                  foreground: *base00
                  deco:
                    stack:
                      - background: {color: *base05}
                      - border:
                          color: *base02
                          size: 3
              selected && ~empty:
                string:
                  margin: 10
                  text: "{name}"
                  foreground: *base05
                  deco:
                    stack:
                      - background: {color: *base00}
                      - border:
                          color: *base02
                          size: 3
                      - underline:
                          color: *base05
                          size: 3
              ~empty:
                string:
                  margin: 10
                  text: "{name}"
                  foreground: *base05
                  deco:
                    stack:
                      - background: {color: *base00}
                      - border:
                          color: *base02
                          size: 3
              selected:
                string:
                  margin: 10
                  text: "{name}"
                  foreground: *base02
                  deco:
                    stack:
                      - background: {color: *base00}
                      - border:
                          color: *base02
                          size: 3
                      - underline:
                          color: *base05
                          size: 3

  right:
    # - network:
    #     poll-interval: 3000
    #     name: "eno2"
    #     content:
    #       map:
    #         default:
    #             string:
    #               text: " ({state})"
    #               foreground: e04040ff
    #               margin: 10
    #               deco: 
    #                 stack: 
    #                   - background: {color: *base00}
    #                   - border: 
    #                       color: *base02
    #                       size: 3
    #         conditions:
    #           state == up:
    #             list:
    #               items:
    #                 - string:
    #                     text: " {ul-speed:mib}MiB/s"
    #                     margin: 10
    #                     foreground: 009020ff
    #                     deco: 
    #                       stack: 
    #                         - background: {color: *base00}
    #                         - border: 
    #                             color: *base02
    #                             size: 3
    #                 - string:
    #                     text: " {dl-speed:mib}MiB/s"
    #                     margin: 10
    #                     foreground: e04040ff
    #                     deco: 
    #                       stack: 
    #                         - background: {color: *base00}
    #                         - border: 
    #                             color: *base02
    #                             size: 3
    - script:
        poll-interval: 3000
        path: "~/.config/yambar/nvidia_gpu.sh"
        content:
          list:
            spacing: 0
            items:
              - string:
                  text: "gpu"
                  margin: 10
                  deco: 
                    stack: 
                      - background: {color: *base00}
                      - border: 
                          color: *base02
                          size: 3
              - string:
                  text: " {gpu_percent_used}%"
                  margin: 10
                  deco: 
                    stack: 
                      - background: {color: *base00}
                      - border: 
                          color: *base02
                          size: 3

              - string:
                  text: " {mem_percent_used}%"
                  margin: 10
                  deco: 
                    stack: 
                      - background: {color: *base00}
                      - border: 
                          color: *base02
                          size: 3
    - label:
        content:
          string:
            text: ""
            margin: 20

    - label:
        content:
          string:
            text: "cpu"
            margin: 10
            deco: 
              stack: 
                - background: {color: *base00}
                - border: 
                    color: *base02
                    size: 3


    - cpu:
        poll-interval: 3000
        content:
          map:
            conditions:
              id == -1:
                - string:
                    text: " {cpu}%"
                    margin: 10
                    deco: 
                      stack: 
                        - background: {color: *base00}
                        - border: 
                            color: *base02
                            size: 3
    - mem:
        poll-interval: 3000
        content:
          string:
            text: " {percent_used}%"
            margin: 10
            deco: 
              stack: 
                - background: {color: *base00}
                - border: 
                    color: *base02
                    size: 3
    - label:
        content:
          string:
            margin: 20
            text: ""

    - pulse:
        content:
          list:
            spacing: 0
            items:
              - string:
                  text: "󰍬 {source_percent}%"
                  margin: 10
                  deco: 
                    stack: 
                      - background: {color: *base00}
                      - border: 
                          color: *base02
                          size: 3
              - string:
                  text: "󰕾 {sink_percent}%"
                  margin: 10
                  deco: 
                    stack: 
                      - background: {color: *base00}
                      - border: 
                          color: *base02
                          size: 3
  center:
    - clock:
        time-format: "%I:%M %p"
        date-format: "%d/%m/%Y (%a %b)"
        content:
          list:
            spacing: 10
            items:
              - string:
                  text: " {time}"
                  margin: 10
                  deco: 
                    stack: 
                      - background: {color: *base00}
                      - border: 
                          color: *base02
                          size: 3
              - string:
                  text: " {date}"
                  margin: 10
                  deco: 
                    stack: 
                      - background: {color: *base00}
                      - border: 
                          color: *base02
                          size: 3


